In [1]:
import numpy as np

In [88]:
# Initialize the value and policy matrix.
gamma = 1
value = np.zeros(101)
policy = np.zeros(101, dtype=int)
reward = np.zeros(101)
reward[100] = 1


# Calculate expected reward for each state-action pair.
def expected_reward(state: int, action: int, p_h: float) -> float:
    global value
    """
    Expected reward for a state-action pair.
    """
    win = state + action
    loss = state - action

    bellman_expectation = p_h * (reward[win] + gamma * value[win]) + (1 - p_h) * (
        reward[loss] + gamma * value[loss]
    )
    return bellman_expectation


# Policy evaluation algorithm.
def policy_evaluation(eps=0.01, p_h=0.25):
    global value, policy
    """
    Find the value function corresponding to each state for a given policy.
    """
    while True:
        delta = 0
        for state in range(1, 100):
            v = value[state]
            value[state] = expected_reward(state, policy[state], p_h)
            delta = max(delta, abs(v - value[state]))

        if delta < eps:
            break

    return value


def policy_improvement(p_h=0.25):
    global policy
    """
    Improving the policy by greedy method.
    """
    policy_stable = True
    for state in range(1, 100):
        old_action = policy[state]

        max_action_val = -np.inf
        max_action = None

        # Iterate over all possible actions for the state state.
        for action in range(1, min(state, 100 - state) + 1):
            action_val = expected_reward(state, action, p_h)

            if action_val > max_action_val:
                max_action_val = action_val
                max_action = action

        policy[state] = max_action

        if old_action != max_action:
            policy_stable = False

    return policy_stable


# Implementing policyt iteration algorithm.
while True:
    policy_evaluation()
    policy_stable = policy_improvement()
    if policy_stable:
        break

In [89]:
policy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

**Value Iteration Algorithm**

In [61]:
# Initialize the value and policy matrix.
gamma = 1
value = np.array([0] * 101)
policy = np.array([0] * 101)
value[100] = 1
reward = value.copy()

In [39]:
def value_iteration():
    while True:
        delta = 0
        for state in range(1, 100):
            old_val = value[state]
            max_action_val = value[state]
            max_action = policy[state]

            for action in range(0, min(state, 100 - state) + 1):
                action_val = expected_reward(state, action, 0.25)

                if action_val > max_action_val:
                    max_action_val = action_val
                    max_action = action

            value[state] = max_action_val
            policy[state] = max_action
            delta = max(delta, abs(old_val - value[state]))

        if delta < 0.00001:
            break

In [71]:
import numpy as np

# Parameters
gamma = 1.0  # Discount factor
p_h = 0.4  # Probability of heads
theta = 1e-5  # Convergence threshold

# Initialize value function and policy
value = np.zeros(101)  # Value function for states 0 to 100
policy = np.zeros(101, dtype=int)  # Policy for states 0 to 100
reward = np.zeros(101)  # Reward for each state
reward[100] = 1  # Reward for reaching state 100


def expected_reward(state: int, action: int, p_h: float) -> float:
    """
    Calculate the expected reward for a given state-action pair.
    """
    win = min(state + action, 100)  # Ensure win state does not exceed 100
    loss = max(state - action, 0)  # Ensure loss state does not go below 0

    # Bellman expectation equation
    bellman_expectation = p_h * (reward[win] + gamma * value[win]) + (1 - p_h) * (
        reward[loss] + gamma * value[loss]
    )
    return bellman_expectation


def value_iteration():
    """
    Perform value iteration to compute the optimal value function and policy.
    """
    global value, policy

    while True:
        delta = 0
        for state in range(1, 100):  # Exclude terminal states 0 and 100
            old_val = value[state]
            max_action_val = float("-inf")
            best_action = 0

            # Iterate over all possible actions
            for action in range(1, min(state, 100 - state) + 1):
                action_val = expected_reward(state, action, p_h)
                if action_val > max_action_val:
                    max_action_val = action_val
                    best_action = action

            # Update value function and policy
            value[state] = max_action_val
            policy[state] = best_action
            delta = max(delta, abs(old_val - value[state]))

        # Check for convergence
        if delta < theta:
            break


def display_results():
    """
    Display the optimal value function and policy.
    """
    print("Optimal Value Function:")
    print(value)
    print("\nOptimal Policy:")
    print(policy)


# Run value iteration
value_iteration()

# Display results
display_results()

Optimal Value Function:
[0.         0.00206467 0.00516393 0.00922521 0.01291015 0.01738521
 0.02306354 0.02781403 0.03227537 0.03768437 0.04346334 0.05035416
 0.05765916 0.0652388  0.06953513 0.07443112 0.08068842 0.08661062
 0.0942125  0.10314328 0.10865867 0.11596637 0.12588597 0.13357982
 0.14414789 0.16       0.16309836 0.16774609 0.17383812 0.17936522
 0.18607801 0.19459549 0.20172108 0.20841305 0.2165275  0.2251952
 0.23553158 0.24648874 0.25785902 0.26430287 0.2716468  0.28103265
 0.2899165  0.30131895 0.31471541 0.32298808 0.3339499  0.34882925
 0.36036994 0.37622196 0.4        0.40309836 0.40774609 0.41383812
 0.41936522 0.42607801 0.43459549 0.44172108 0.44841305 0.4565275
 0.4651952  0.47553158 0.48648874 0.49785902 0.50430287 0.5116468
 0.52103265 0.5299165  0.54131895 0.55471541 0.56298808 0.5739499
 0.58882925 0.60036994 0.61622196 0.64       0.64464765 0.65161913
 0.6607573  0.66904783 0.67911712 0.69189324 0.70258172 0.71261959
 0.72479137 0.73779285 0.75329755 0.769733

In [68]:
# Implementing policyt iteration algorithm.
while True:
    policy_stable = value_iteration()
    if policy_stable:
        break

In [69]:
policy

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [70]:
value

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])